### ISSUE TITLE
Support for Changing Spreadsheet Templates (without changing button Actions)

### ISSUE THREAD

**Issue by davidjoshuaford** [bitfocus/companion-module-google-sheets#4]
**Describe the feature**
The current drop-down menu in the Actions for sheets means you need to identify a specific sheet. The problem is if you build out many actions to a specific spreadsheet, but then change spreadsheets, you have to manually go through every action and update which spreadsheet the Action targets.

**Usecases**
Example is creating a Run Of Show template in Sheets. You then build a whole page of Companion buttons that will trigger based on data in your ROS template sheet. 

Then you duplicate the ROS template for the next show, but you want all of your button Actions that you designed in Companion to reference the data in the new spreadsheet. 

Currently you'd have to find all Sheet Actions in Companion and manually update each action to the new spreadsheet. 

Not 100% sure what the solution is here, but perhaps it is having Actions that are tied to spreadsheet ID numbers (such that if you swap Spreadsheet ID numbers, the Action will still identify the identical Sheet Name within the spreadsheet workbook).

<img width="884" alt="Screen Shot 2022-08-25 at 11 25 51 AM" src="https://user-images.githubusercontent.com/76959770/186706738-22805df0-392f-48c1-aba0-8da94f037666.png">

**Comment by thedist** [comment]
In the next beta version I've attempted to create a solution for this by creating an option in the config to reference spreadsheets by index, rather than ID.

What this means is that by default actions/feedbacks/variables reference by ID, so it doesn't matter which order you provide sheet ids it'll always reference that spreadsheet (as things currently work). If the config option is toggled to reference by index it means you can instead set the Spreadsheet to whichever is the first, second, third, etc... in the space separated list in the config. That way if you want all your actions/feedbacks/variables to work on a different spreadsheet, you can just reorder the spreadsheet ids in the config.

**Comment by davidjoshuaford** [comment]
Sounds good, I'll check it out, thanks!
